In [11]:
from scipy.spatial import KDTree
import numpy as np

In [12]:
N_points = 1000000

data = np.random.random([N_points,3])
data

array([[0.16185198, 0.3326144 , 0.21635199],
       [0.74894455, 0.85571338, 0.04166299],
       [0.68532585, 0.88423538, 0.02521935],
       ...,
       [0.04514626, 0.04665844, 0.71752648],
       [0.98762683, 0.54586611, 0.1818482 ],
       [0.17888023, 0.48227292, 0.75951363]])

In [13]:
data_KDT = KDTree(data)
data_KDT.data

array([[0.16185198, 0.3326144 , 0.21635199],
       [0.74894455, 0.85571338, 0.04166299],
       [0.68532585, 0.88423538, 0.02521935],
       ...,
       [0.04514626, 0.04665844, 0.71752648],
       [0.98762683, 0.54586611, 0.1818482 ],
       [0.17888023, 0.48227292, 0.75951363]])

In [14]:
data_KDT.query_ball_point([0.53,0.247,0.5301], 0.08)

[114930,
 866619,
 74733,
 227323,
 403078,
 893546,
 393800,
 129441,
 21211,
 221845,
 507942,
 133403,
 568638,
 790199,
 75930,
 403665,
 539736,
 167158,
 123703,
 633489,
 687336,
 790790,
 857180,
 156509,
 203407,
 120813,
 774440,
 408836,
 252923,
 412000,
 539112,
 264149,
 111931,
 755330,
 354845,
 697794,
 676210,
 978889,
 637456,
 913389,
 982994,
 104684,
 696270,
 970436,
 165082,
 594874,
 175464,
 214260,
 808971,
 444075,
 835312,
 443811,
 47101,
 17200,
 549676,
 856782,
 472780,
 207683,
 901438,
 233265,
 765279,
 50254,
 219860,
 319501,
 906768,
 721307,
 493407,
 136815,
 929430,
 651482,
 372199,
 302733,
 893924,
 87678,
 317643,
 374826,
 833828,
 9351,
 639878,
 270197,
 8934,
 279397,
 484889,
 216639,
 499567,
 345310,
 449385,
 532379,
 760832,
 354583,
 434721,
 583778,
 114179,
 331967,
 965563,
 771689,
 946362,
 6565,
 847802,
 72505,
 672321,
 618568,
 853031,
 864207,
 558695,
 108180,
 946101,
 937504,
 272613,
 294425,
 123821,
 793104,
 57699

In [40]:
l = [4,5,2,7,5,1,2,10]
l[1:-1]

[5, 2, 7, 5, 1, 2]

In [16]:
l[0:1]

[4]

In [27]:
np.random.choice(l, 4, replace=False)

array([ 5,  2,  5, 10])

In [29]:
for i in range(1,2):
    print(i)

1


In [32]:
l = [1]
if l == []:
    print("ao")

In [39]:
c = 2
np.array([[0,4,3],[4,3,2],[45,43] if c==3 else [5,4]], dtype=object)

array([list([0, 4, 3]), list([4, 3, 2]), list([5, 4])], dtype=object)